### PR TITLE
Fix incorrect escaping of large payloads (focused PR)

### LINKED ISSUE #4: Quotes / double escaping issue
Ruby: 3.4 preview
Rails: Edge
Postgresql: 17rc1

I'm running into an issue when my payload becomes large enough to trigger the special handling of this adapter. I'm rendering responses on the server side like this:

```ruby
def broadcast
  html = ApplicationController.render(partial: "my/partial", layout: false)
  broadcast_action_later_to self, action: "replace", target: dom_id(self), html:
end
```

The page is updated with the correct markup when using the async adapter, or the enhanced_postgresql adapter when the response is small enough:

```html
<div>
  <h1 class="font-bold text-xxl">Placeholder heading</h1>
</div>
```

But when the payload is large enough to trigger a read from `action_cable_large_payloads`, the markup looks like this:

```html
<div>
  <h1 class="" font-bold="" text-xxl''="">Placeholder heading</h1>
</div>
```

### PR DESCRIPTION
**Pull request by bensheldon**
Extracts the bugfix of #5 while removing the Dockerized test setup changes. 

I was hopeful that the more focused change would be more palatable for merging upstream in case that added friction to reviewing the other PR. 

Fixes #4. 

I did make one test setup change 🥵  `active_support/testing/strict_warnings` was moved out of LOAD_PATH: https://github.com/rails/rails/pull/54617

(fyi @chriscz who authored #5)

### CODE REVIEW

File: test/test_helper.rb [hunk 1]
```diff
@@ -1,8 +1,11 @@
 # frozen_string_literal: true
 
 require "debug"
-
-require "active_support/testing/strict_warnings"
+begin
+  require "active_support/testing/strict_warnings"
```
Comment (dbackeus) [inline test/test_helper.rb:5]: I don't quite remember what this used to do TBH. I guess it was removed in Rails 8. Maybe ok to just remove the require altogether.

**Comment by dbackeus** [comment]
Thanks for this!

Don't know why but I haven't received github notifications for the issues / pull requests on this repo which is why I didn't take action until I saw your ping on the Reclaim the Stack Discord.

**Comment by dbackeus** [comment]
Released in v1.0.2

https://rubygems.org/gems/actioncable-enhanced-postgresql-adapter
https://github.com/reclaim-the-stack/actioncable-enhanced-postgresql-adapter/blob/master/CHANGELOG.md
